id: '1599528072992'
alias: Vacation Living Room Hub
description: ''
trigger:
- entity_id: sensor.vacation_living_room_hub
  platform: state
condition:
- condition: state
  entity_id: input_boolean.vacation_mode
  state: 'on'
action:
- data: {}
  entity_id: remote.living_room_hub
  service: light.toggle
mode: single