light templates:
- platform: template
  lights:
    dining_room_light:
      friendly_name: Dining Room Light
      value_template: "{{ is_state('group.dining_room_light', 'on') }}"
      turn_on:
        service: light.turn_on
        entity_id: group.dining_room_light
      turn_off:
        service: light.turn_off
        entity_id: group.dining_room_light
- platform: template
  lights:
    bedroom_lights:
      friendly_name: Bedroom Lights
      value_template: "{{ is_state('group.bedroom_lights', 'on') }}"
      turn_on:
        service: light.turn_on
        entity_id: group.bedroom_lights
      turn_off:
        service: light.turn_off
        entity_id: group.bedroom_lights
- platform: template
  lights:
    all_dunn_bar_lights:
      friendly_name: All Dunn Bar Lights
      value_template: "{{ is_state('group.all_dunn_bar_lights', 'on') }}"
      turn_on:
        service: light.turn_on
        entity_id: group.all_dunn_bar_lights
      turn_off:
        service: light.turn_off
        entity_id: group.all_dunn_bar_lights
- platform: template
  lights:
    boys_room_lights:
      friendly_name: Boys Room Lights
      value_template: "{{ is_state('group.boys_room_lights', 'on') }}"
      turn_on:
        service: light.turn_on
        entity_id: group.boys_room_lights
      turn_off:
        service: light.turn_off
        entity_id: group.boys_room_lights
- platform: template
  lights:
    teagans_room_lights:
      friendly_name: "Teagan's Room Lights"
      value_template: "{{ is_state('group.teagans_room_lights', 'on') }}"
      turn_on:
        service: light.turn_on
        entity_id: group.teagans_room_lights
      turn_off:
        service: light.turn_off
        entity_id: group.teagans_room_lights
- platform: template
  lights:
    upstairs_hallway_light:
      friendly_name: Upstairs Hallway Light
      value_template: "{{ is_state('group.upstairs_hallway_light', 'on') }}"
      turn_on:
        service: light.turn_on
        entity_id: group.upstairs_hallway_light
      turn_off:
        service: light.turn_off
        entity_id: group.upstairs_hallway_light
- platform: template
  lights:
    upstairs_kitchen_light:
      friendly_name: Upstairs Kitchen Light
      value_template: "{{ is_state('group.upstairs_kitchen_light', 'on') }}"
      turn_on:
        service: light.turn_on
        entity_id: group.upstairs_kitchen_light
      turn_off:
        service: light.turn_off
        entity_id: group.upstairs_kitchen_light
- platform: template
  lights:
    upstairs_living_room_light:
      friendly_name: Upstairs Living Room Light
      value_template: "{{ is_state('group.upstairs_living_room_light', 'on') }}"
      turn_on:
        service: light.turn_on
        entity_id: group.upstairs_living_room_light
      turn_off:
        service: light.turn_off
        entity_id: group.upstairs_living_room_light
- platform: template
  lights:
    living_room_light:
      friendly_name: Living Room Light
      value_template: "{{ is_state('group.living_room_light', 'on') }}"
      turn_on:
        service: light.turn_on
        entity_id: group.living_room_light
      turn_off:
        service: light.turn_off
        entity_id: group.living_room_light
- platform: template
  lights:
    outdoor_lights:
      friendly_name: Outdoor Lights
      value_template: "{{ is_state('group.outdoor_lights', 'on') }}"
      turn_on:
        service: light.turn_on
        entity_id: group.outdoor_lights
      turn_off:
        service: light.turn_off
        entity_id: group.outdoor_lights
- platform: template
  lights:
    garage_lights:
      friendly_name: Garage Lights
      value_template: "{{ is_state('group.garage_lights', 'on') }}"
      turn_on:
        service: light.turn_on
        entity_id: group.garage_lights
      turn_off:
        service: light.turn_off
        entity_id: group.garage_lights
