switch:
- platform: template
  switches:
    living_room_fireplace:
      friendly_name: Living Room Fireplace
      value_template: "{% if is_state('input_boolean.living_room_fireplace', 'on') %}on{% else %}off{% endif %}"
      turn_on:
      - service: remote.send_command
        data:
          entity_id: remote.living_room_hub
          command:
            - PowerToggle
          device: Living Room Fireplace
      turn_off:
      - service: remote.send_command
        data:
          entity_id: remote.living_room_hub
          command:
            - PowerToggle
          device: Living Room Fireplace
- platform: template
  switches:
    ender3:
      friendly_name: Ender3
      value_template: "{{ is_state('switch.3d_printer_psu', 'on') }}"
      turn_on:
        service: switch.turn_on
        data:
          entity_id: switch.3d_printer_psu
      turn_off:
        service: script.ender3_safe_power_down
- platform: template
  switches:
    bedroom_room_light:
      friendly_name: bedroom Light
      value_template: "{{ is_state('light.bedroom_light', 'on') }}"
      turn_on:
        service: light.turn_on
        entity_id: light.bedroom_light
      turn_off:
        service: light.turn_off
        entity_id: light.bedroom_light