# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

script: !include scripts.yaml
homeassistant:
  name: Dunn Compound
  currency: USD
  customize: !include customize.yaml
  packages: !include_dir_named integrations

ffmpeg:

frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/hass-bha-icons/hass-bha-icons.js
    - /hacsfiles/custom-sidebar/custom-sidebar.js
    - /hacsfiles/hass-hue-icons/hass-hue-icons.js
    - /hacsfiles/lovelace-card-mod/card-mod.js